#!/bin/zsh
while /bin/true
do
#echo "\nReady >>\n"
echo "\n\x1b[33mReady >>\x1b[0m\n"
inotifywait -rqq -e close_write src SpaceSim
echo "\n\x1b[33mCompiling...\x1b[0m\n"
make debug 2>&1 \
	| sed -e 's/[a-zA-Z_\/\.]*\.\(c\|h\|o\|moon\|lua\)/\x1b[32m&\x1b[0m/' \
	| sed -e 's/[a-zA-Z_\/\.]*\.\(lua\)/\x1b[32m&\x1b[0m/' \
	| sed -e 's/.*error.*/\x1b[31m\[error\]\x1b[0m&/' \
	| sed -e 's/.*Failed to parse.*/\x1b[31m\[error\]\x1b[0m&/' \
	| grep -v "Nothing to be done for"
done
